services:
  structurizr:
    image: structurizr/onpremises
    container_name: structurizr-onpremise-c4-model-demo-finale
    ports:
      - "8088:8080"  # Expose container's port 8088
    volumes:
      - ./structurizr-data-store:/usr/local/structurizr  # Mount local data directory
    environment:
      - STRUCTURIZR_PROPERTIES_FILE=/usr/local/structurizr/structurizr.properties
